spring:
  redis: # redis 配置
    host: localhost # Redis服务器地址
    port: 6379  # Redis服务器连接端口
    pool:
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
      max-active: 80  # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）

management:
  security:
    enabled: false    # springboot 1.5.x 以上默认开通了安全认证，所以需要在配置文件application.yml添加此配置，以post请求的方式来访问http://localhost:8081/refresh 就会更新修改后的配置文件