server:
  port: 10002
spring:
  redis:
    host: localhost # Redis服务器地址
    port: 6379  # Redis服务器连接端口
    database: 0
    password:
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 0
  cloud:
    bus:
      trace:
        enabled: true
      enabled: true
  rabbitmq:
    host: 192.168.99.100
    port: 32775
    username: guest
    password: guest
deveb:
  test: Quinn
